#!/bin/bash

# Script to generate localization strings
# Usage: ./gen_strings.sh

set -e

echo "Generating localization strings..."

# Create English strings file if it doesn't exist
ENGLISH_STRINGS="Resources/Localizations/en.lproj/Localizable.strings"
if [ ! -f "$ENGLISH_STRINGS" ]; then
    mkdir -p "Resources/Localizations/en.lproj"
    touch "$ENGLISH_STRINGS"
fi

# Create Korean strings file if it doesn't exist
KOREAN_STRINGS="Resources/Localizations/ko.lproj/Localizable.strings"
if [ ! -f "$KOREAN_STRINGS" ]; then
    mkdir -p "Resources/Localizations/ko.lproj"
    touch "$KOREAN_STRINGS"
fi

# Find all Swift files and extract NSLocalizedString calls
echo "Scanning for localization keys..."

# Extract NSLocalizedString calls
find . -name "*.swift" -exec grep -H "NSLocalizedString\|\.localized" {} \; > /tmp/localized_strings.txt

# Generate strings file (basic implementation)
echo "/* Generated localization strings */" > "$ENGLISH_STRINGS"
echo "/* Do not edit this file manually */" >> "$ENGLISH_STRINGS"
echo "" >> "$ENGLISH_STRINGS"

# Add common strings
cat >> "$ENGLISH_STRINGS" << 'EOF'
/* Common */
"app.name" = "BedTimer";
"app.version" = "Version %@";

/* Alarm */
"alarm.start_countdown" = "Start Countdown";
"alarm.snooze" = "Snooze";
"alarm.out_of_bed" = "Out of Bed";
"alarm.goal_reached" = "Goal Reached!";

/* Sessions */
"session.start" = "Start Session";
"session.end" = "End Session";
"session.delete" = "Delete";
"session.delete_confirm" = "Are you sure you want to delete this session?";

/* Settings */
"settings.notifications" = "Notifications";
"settings.privacy" = "Privacy";
"settings.about" = "About";

/* Widgets */
"widget.countdown" = "Countdown";
"widget.streak" = "Streak";
"widget.weekly_average" = "Weekly Average";

/* Watch */
"watch.start" = "Start";
"watch.stop" = "Stop";
"watch.snooze" = "Snooze";
EOF

echo "Localization strings generated!"
echo "English: $ENGLISH_STRINGS"
echo "Korean: $KOREAN_STRINGS"
echo ""
echo "Next steps:"
echo "1. Review and edit the generated strings"
echo "2. Add Korean translations"
echo "3. Test localization in the app"