name: Release to TestFlight

on:
  push:
    tags: [ 'v*' ]

jobs:
  release:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      
      - uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: '16.0'
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: Tooling/fastlane
      
      - name: Install Fastlane
        run: |
          cd Tooling/fastlane
          bundle install
      
      - name: Decrypt signing
        run: ./Tooling/scripts/decrypt_signing.sh
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      
      - name: Fastlane deliver
        run: cd Tooling/fastlane && bundle exec fastlane ios beta
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      
      - name: Upload to TestFlight
        run: |
          echo "Release ${{ github.ref_name }} deployed to TestFlight"